name: React 17

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  react17:
    name: Test in React 17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install node-gyp
        run: yarn global add node-gyp

      - name: Install package.json
        run: yarn install --prefer-offline

      - name: Build CLI
        run: yarn build:cli

      # TODO: Will nohoist help here?
      - name: Install testing tools for React 17
        run: npx ts-node tools/test/scripts/install-react17.ts

      - name: Build packages
        run: yarn build

      - name: Run tests in React 17
        run: yarn lg test --react17
